from .users import user_router
from .extractors import extractor_router
from .companies import company_router
from .addresses import address_router
from .customers import customer_router
from .beer_types import beer_type_router
from .kegs import keg_router
from .beer_dispensers import beer_dispenser_router
from .pressure_gauges import pressure_gauge_router
from .reservations import reservation_router
from .dashboard import dashboard_router
from .cylinders import cylinder_router
