from .addresses import address_router
from .beer_dispensers import beer_dispenser_router
from .beer_types import beer_type_router
from .companies import company_router
from .customers import customer_router
from .cylinders import cylinder_router
from .dashboard import dashboard_router
from .extraction_kits import extraction_kit_router
from .kegs import keg_router
from .payments import payment_router
from .reservations import reservation_router
from .users import user_router
