name: Barriil Club API CI Pipeline

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev" ]

permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      # - name: Test with pytest
      #   run: |
      #     pytest

      # - name: Login to DockerHub
      #   if: github.ref == 'refs/heads/dev'
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ vars.DOCKER_USERNAME }}
      #     password: ${{ vars.DOCKER_TOKEN }}

      # - name: Build, Barriil Club API
      #   if: github.ref == 'refs/heads/dev'
      #   run: |
      #     docker build -t ${{ vars.DOCKER_USERNAME }}/${{ vars.MY_REPOSITORY_NAME }}:${{ github.sha }} .
      #     docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.MY_REPOSITORY_NAME }}:${{ github.sha }}
